[program:kibondo-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/kibondo/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --timeout=30
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/kibondo-worker.log
stopwaitsecs=3600
